var namespacede_1_1telekom_1_1pde_1_1codelibrary_1_1samples_1_1datavisualisation_1_1usagecircle =
[
    [ "UsageCircleOverviewActivity", "classde_1_1telekom_1_1pde_1_1codelibrary_1_1samples_1_1datavisualisation_1_1usagecircle_1_1_usage_circle_overview_activity.html", "classde_1_1telekom_1_1pde_1_1codelibrary_1_1samples_1_1datavisualisation_1_1usagecircle_1_1_usage_circle_overview_activity" ],
    [ "UsageCircleProgrammingSample", "classde_1_1telekom_1_1pde_1_1codelibrary_1_1samples_1_1datavisualisation_1_1usagecircle_1_1_usage_circle_programming_sample.html", "classde_1_1telekom_1_1pde_1_1codelibrary_1_1samples_1_1datavisualisation_1_1usagecircle_1_1_usage_circle_programming_sample" ],
    [ "UsageCircleResizingSample", "classde_1_1telekom_1_1pde_1_1codelibrary_1_1samples_1_1datavisualisation_1_1usagecircle_1_1_usage_circle_resizing_sample.html", "classde_1_1telekom_1_1pde_1_1codelibrary_1_1samples_1_1datavisualisation_1_1usagecircle_1_1_usage_circle_resizing_sample" ]
];