var namespacede_1_1telekom_1_1pde_1_1codelibrary_1_1samples_1_1graphicelements =
[
    [ "GfxPrimitivesResizeActivity", "classde_1_1telekom_1_1pde_1_1codelibrary_1_1samples_1_1graphicelements_1_1_gfx_primitives_resize_activity.html", "classde_1_1telekom_1_1pde_1_1codelibrary_1_1samples_1_1graphicelements_1_1_gfx_primitives_resize_activity" ]
];